- name: Setting up a remote server
  hosts: piwigo-droplet
  connection: local #change?
  #debugger: on_skipped
  debugger: on_failed
  become: true
  pre_tasks:
    - name: update repositories
      apt:
            update_cache=yes
            upgrade=dist # to resolve the warning message "Could not find aptitude. Using apt-get instead"
      changed_when: False
  roles:
    #https://github.com/vitalk/ansible-secure-ssh
    - role: vitalk.secure-ssh
      ssh_user: piwigo,
      ssh_identity_key: /home/{{ansible_facts['user_id']}}/.ssh/id_rsa4.pub }
    - role: piwigo
        vars:
          apache_vhosts:
            - {servername: "photos.wildintellect.com", documentroot: "/var/www/photos", serveradmin: "tech@wildintellect.com"}
    
    # This needs mariadb password settings - do they go here or in a .env file
