
---
# Install Apache2 HTTP
# Included in LAMP droplet so we just need to configure
#- name: Install Apache2
#  apt:
#    name:
#      - nginx
#    state: present
#    autoclean: yes
#    update_cache: true

# Install Config files
- name: Create virtual host file
  template:
    src: vhost.conf
    dest: /etc/apache2/sites-available/{{ servername }}.conf

- name: Create virtual host file ssl
  template:
    src: vhost-ssl.conf
    dest: /etc/apache2/sites-available/{{ servername }}-ssl.conf

# Enable configs
- name: a2ensite {{ servername }}
  command: a2ensite {{ servername }}
  args:
    creates: /etc/apache2/sites-enabled/{{ servername }}.conf

- name: a2ensite {{ domain }}-ssl
  command: a2ensite {{ servername }}-ssl
  args:
    creates: /etc/apache2/sites-enabled/{{ servername }}-ssl.conf
  notify:
  - restart apache2


# Configure Mode
- name: Configure Apache mpm
  apache2_module:
    state: present
    name: mpm_event
    ignore_configcheck: False

# Configure Nginx
# Do we want to use php-fpm probably
# https://howto.wared.fr/installation-piwigo-nginx-mariadb-ubuntu/
# https://websiteforstudents.com/install-the-piwigo-photo-gallery-on-ubuntu-16-04-17-10-18-04-with-apache2-mariadb-and-php-7-2-support/
