---
# Install Apache2 HTTP
# Included in LAMP droplet so we just need to configure
#- name: Install Apache2
#  apt:
#    name:
#      - nginx
#    state: present
#    autoclean: yes
#    update_cache: true

# Install Config files
- name: Create virtual host file
  template:
    src: vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ servername }}.conf"

#- name: Create virtual host file ssl
#  template:
#    src: vhost-ssl.conf.j2
#    dest: "/etc/apache2/sites-available/{{ servername }}-ssl.conf"

# Enable configs
- name: a2dissite default
  command: a2dissite 000-default.conf

# Enable configs
- name: "a2ensite {{ servername }}"
  command: "a2ensite {{ servername }}"
  args:
    creates: "/etc/apache2/sites-enabled/{{ servername }}.conf"

#- name: "a2ensite {{ servername }}-ssl"
#  command: "a2ensite {{ servername }}-ssl"
#  args:
#    creates: "/etc/apache2/sites-enabled/{{ servername }}-ssl.conf"
#  notify:
#  - reload apache2

# Try to setup certbot, problem is it's interactive
#- name: Certbot
#  command: "certbot --apache -d {{ servername }}"
# SSL Fails, lack of certs
#- name: Configure Apache SSL
#  apache2_module:
#    state: present
#    name: ssl
#    ignore_configcheck: True

# Configure Mode
# Need to disable php7.4 for this to work, which mean php-fpm needs to be installed
#- name: Configure Apache mpm
#  apache2_module:
#    state: absent
#    name: mpm_prefork
#    ignore_configcheck: True

#- name: Configure Apache mpm
#  apache2_module:
#    state: present
#    name: mpm_event
#    ignore_configcheck: True
#  notify:
#  - restart apache2


# Configure Nginx
# Do we want to use php-fpm probably
# https://howto.wared.fr/installation-piwigo-nginx-mariadb-ubuntu/
# https://websiteforstudents.com/install-the-piwigo-photo-gallery-on-ubuntu-16-04-17-10-18-04-with-apache2-mariadb-and-php-7-2-support/
